#!/usr/bin/env python3
"""
This script parses the filemap.yaml file and outputs the changes it
would make to the targets on the current system (default: DRYRUN=true).
"""

import os
import sys
from pylib import deploy

filemap = "filemap.yaml"
if len(sys.argv) > 1:
    filemap = sys.argv[1]

if os.environ.get("DRYRUN") == "false":
    deploy.push(filemap)
else:
    deploy.preview(filemap)
