#!/usr/bin/env python3
"""
This script parses the filemap.yaml file and outputs the changes it
would make to the targets on the current system (default: DRYRUN=true).
"""

import sys
import yaml
from pylib import pylib

if len(sys.argv) > 1:
    items = pylib.parse_filemap(sys.argv[1])
else:
    items = pylib.parse_filemap()

for item in items:
    print(f"source: {item["source"]}")
    if not pylib.applies_to_host(item): continue
    if not pylib.source_exists(item):   continue

