# Old Syntax: HOST[,HOST...] SOURCE TARGET [OWNER[:GROUP]] [CHMOD_PERMS] [OPTIONS]

- hosts: [localhost, iknowthis]
  source: src/myscript
  target: /tmp/myscript

- hosts: [localhost, iknowthis]
  source: src/scripts/
  target: ~/local/bin
  owner: rwxrob
  group: everyone
  options:
    - recurse

- hosts: [localhost, iknowthis]
  source: src/justadir/
  target: /tmp/justadir
  perms: 700

- hosts: [somethingelseentirely]
  source: src/bar
  target: /tmp/bar
  perms: +x
